services:
  server:
    build: server
    ports:
      - 5000:5000
    env_file: .env
    environment:
      CI: "1"
      CLICOLOR_FORCE: "1"
    tty: true

  client:
    build: client
    ports:
      - 3000:3000
    env_file: .env
    environment:
      TERM: xterm-256color
    tty: true
