apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  namespace: mutclip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: localhost:31509/mutclip-client
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: env
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: mutclip
spec:
  selector:
    app: client
  ports:
  - port: 3000
    targetPort: 3000
