apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: mutclip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: aantonm/mutclip:server
        resources:
          limits:
            memory: 30Mi
            cpu: 300m
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: env
      imagePullSecrets:
      - name: dockerconfig
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: mutclip
spec:
  selector:
    app: server
  ports:
  - port: 5000
    targetPort: 5000
